import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home({ films }) {
 
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="films">

        {films.results.map((film, index) => (
          <Link href={`/film/${index +1 }`} passHref>
            <div key={film.title} className="film">
              <Image
                src={`/images/${film.episode_id}.jpg`}
                alt="Picture of the author"
                width={300}
                height={500}
              />
              <h3> {film.title}</h3>
            </div>
          </Link>
        ))}
      </section>
    </div>
  );
}

// This function gets called at build time
export async function getStaticProps() {
  // Call an external API endpoint to get posts
  const res = await fetch("https://swapi.dev/api/films");
  const films = await res.json();

  return {
    props: {
      films,
    },
  };
}
